"""create_resumes_and_profile_field_meta_tables

Revision ID: 4259d1296208
Revises: 
Create Date: 2026-10-01 10:56:05.143837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.user


# revision identifiers, used by Alembic.
revision: str = '4259d1296208'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('profile_field_meta',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('profile_id', app.models.user.GUID(), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_span', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_field_meta_profile_id'), 'profile_field_meta', ['profile_id'], unique=False)
    op.add_column('master_profiles', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('master_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('master_profiles', sa.Column('created_from_resume_id', app.models.user.GUID(), nullable=True))
    op.add_column('master_profiles', sa.Column('data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_master_profiles_created_from_resume_id'), 'master_profiles', ['created_from_resume_id'], unique=False)
    op.create_index(op.f('ix_master_profiles_is_active'), 'master_profiles', ['is_active'], unique=False)
    op.create_foreign_key('fk_master_profiles_created_from_resume_id', 'master_profiles', 'resumes', ['created_from_resume_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_master_profiles_created_from_resume_id', 'master_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_master_profiles_is_active'), table_name='master_profiles')
    op.drop_index(op.f('ix_master_profiles_created_from_resume_id'), table_name='master_profiles')
    op.drop_column('master_profiles', 'data')
    op.drop_column('master_profiles', 'created_from_resume_id')
    op.drop_column('master_profiles', 'is_active')
    op.drop_column('master_profiles', 'version')
    op.drop_index(op.f('ix_profile_field_meta_profile_id'), table_name='profile_field_meta')
    op.drop_table('profile_field_meta')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
